cidr_networks:
  container: 10.0.32.0/20
  tunnel: 10.0.19.0/24
  storage: 10.0.16.0/24
  lbaas: 172.30.0.0/16
used_ips:
  - "10.0.19.1,10.0.19.50"
  - "10.0.18.1,10.0.18.50"
  - "10.0.16.1,10.0.16.50"
  - "172.30.1.0,172.30.3.255" 
global_overrides:
  internal_lb_vip_address: 10.0.47.254
  external_lb_vip_address: cloud.zeroone.tech
  management_bridge: "br-mgmt"
  provider_networks: "" 
  neutron_provider_networks:
    network_types: "geneve"
    network_geneve_ranges: "1:10000"
    network_vlan_ranges: "public,lbaas,vlan:1120:1129,vlan:3000:3001,vlan:4001:4001"
    network_mappings: "public:br-wan,lbaas:br-lbaas,vlan:br-vlan"
    network_interface_mappings: "br-wan:bond0.4000,br-lbaas:bond0.1102,br-vlan:bond0"
    #  provider_networks:
    #   - network:
    #        group_binds:
    #          - neutron_ovn_controller
    #        container_bridge: "br-gen"
    #        container_type: "veth"
    #        container_mtu: "9000"
    #        ip_from_q: "tunnel"
    #        type: "geneve"
    #        range: "1:1000"
    #        net_name: "geneve"
    #        network_interface: "bond0.1101"
    #   - network:
    #        group_binds:
    #          - neutron_ovn_controller
    #        container_bridge: "br-wan"
    #        container_type: "veth"
    #        type: "flat"
    #        net_name: "public"
    #        network_interface: "eth99"
    #   - network:
    #       group_binds:
    #         - neutron_ovn_controller
    #       container_bridge: "br-vlan"
    #       container_type: "veth"
    #       type: "vlan"
    #       net_name: "vlan"
    #       range: "1120:1129"
    #       network_interface: "bond0"
    #   - network:
    #       group_binds:
    #         - neutron_ovn_controller
    #         - octavia-worker
    #         - octavia-housekeeping
    #         - octavia-health-manager
    #       container_bridge: "br-lbaas"
    #       container_type: "veth"
    #       type: "flat"
    #       net_name: "lbaas"
    #       network_interface: "bond0.1102"
    #       container_interface: "br-lbaas"
_zun_hosts: &zun
  m710x-c1n1:
    management_ip: 10.0.13.18
    ip: 10.0.33.0
  m710x-c2n1:
    management_ip: 10.0.13.19
    ip: 10.0.33.1
  m710x-c3n1:
    management_ip: 10.0.13.20
    ip: 10.0.33.2
_infra_hosts: &infra
  infra-01:
    management_ip: 10.0.13.10
    ip: 10.0.32.4
    no_containers: true
    host_vars:
      nova_nova_conf_overrides:
        DEFAULT:
          #          internal_service_availability_zone: "{{ availability_zone }}"
          default_availability_zone: "{{ availability_zone }}"
          default_schedule_zone: "{{ availability_zone }}"
        cinder:
          cross_az_attach: True
  infra-02:
    management_ip: 10.0.13.11
    ip: 10.0.32.5
    no_containers: true
    host_vars:
      nova_nova_conf_overrides:
        DEFAULT:
          #        internal_service_availability_zone: "{{ availability_zone }}"
        default_availability_zone: "{{ availability_zone }}"
        default_schedule_zone: "{{ availability_zone }}"
      cinder:
        cross_az_attach: True
  infra-03:
    management_ip: 10.0.13.12
    ip: 10.0.32.6
    no_containers: true
    host_vars:
      nova_nova_conf_overrides:
        DEFAULT:
          #          internal_service_availability_zone: "{{ availability_zone }}"
          default_availability_zone: "{{ availability_zone }}"
          default_schedule_zone: "{{ availability_zone }}"
        cinder:
          cross_az_attach: True
_compute_hosts: &compute
  #  compute-01:
  #    ip: 10.0.32.7
  #    host_vars: 
  #      nova_nova_conf_overrides:
  #        DEFAULT:
  #          internal_service_availability_zone: "{{ availability_zone }}"
  #          default_availability_zone: "{{ availability_zone }}"
  #          default_schedule_zone: "{{ availability_zone }}"
  #        cinder:
  #          cross_az_attach: True
  #  compute-02:
  #    ip: 10.0.32.8
  #    host_vars:
  #      nova_nova_conf_overrides:
  #        DEFAULT:
  #          internal_service_availability_zone: "{{ availability_zone }}"
  #          default_availability_zone: "{{ availability_zone }}"
  #          default_schedule_zone: "{{ availability_zone }}"
  #        cinder:
  #          cross_az_attach: True
  #        libvirt:
  #          cpu_mode: custom
  #          cpu_models: Skylake-Server-noTSX-IBRS
  #  compute-03:
  #    ip: 10.0.32.9
  #    host_vars:
  #      nova_nova_conf_overrides:
  #        DEFAULT:
  #          internal_service_availability_zone: "{{ availability_zone }}"
  #          default_availability_zone: "{{ availability_zone }}"
  #          default_schedule_zone: "{{ availability_zone }}"
  #        cinder:
  #          cross_az_attach: True  
  #        libvirt:
  #          cpu_mode: custom
  #          cpu_models: Skylake-Server-noTSX-IBRS
  #  compute-04:
  #    ip: 10.0.32.10
  # lvw-380g10-comp5:
  #   ip: 10.0.32.11
  #   host_vars:
  #     nova_nova_conf_overrides:
  #       DEFAULT:
  #         internal_service_availability_zone: "{{ availability_zone }}"
  #         default_availability_zone: "{{ availability_zone }}"
  #         default_schedule_zone: "{{ availability_zone }}"
  #       cinder:
  #         cross_az_attach: True
  #       libvirt:
  #         cpu_mode: custom
  #         cpu_models: Skylake-Server-noTSX-IBRS
  lvw-380g10-comp2:
    management_ip: 10.0.13.14
    ip: 10.0.32.8
    host_vars:
      nova_nova_conf_overrides:
        DEFAULT:
          internal_service_availability_zone: "{{ availability_zone }}"
          default_availability_zone: "{{ availability_zone }}"
          default_schedule_zone: "{{ availability_zone }}"
        cinder:
          cross_az_attach: True
        libvirt:
          cpu_mode: custom
          cpu_models: Skylake-Server-noTSX-IBRS
  lvw-380g10-comp3:
    management_ip: 10.0.13.15
    ip: 10.0.32.9
    host_vars:
      nova_nova_conf_overrides:
        DEFAULT:
          default_availability_zone: "{{ availability_zone }}"
          default_schedule_zone: "{{ availability_zone }}"
        cinder:
          cross_az_attach: True
        libvirt:
          cpu_mode: custom
          cpu_models: Skylake-Server-noTSX-IBRS
  lvw-380g10-comp4:
    management_ip: 10.0.13.16
    ip: 10.0.32.10
    host_vars:
      nova_nova_conf_overrides:
        DEFAULT:
          default_availability_zone: "{{ availability_zone }}"
          default_schedule_zone: "{{ availability_zone }}"
        cinder:
          cross_az_attach: True
        libvirt:
          cpu_mode: custom
          cpu_models: Skylake-Server-noTSX-IBRS
  lvw-380g10-comp5:
    management_ip: 10.0.13.17
    ip: 10.0.32.11
    host_vars:
      nova_nova_conf_overrides:
        DEFAULT:
          default_availability_zone: "{{ availability_zone }}"
          default_schedule_zone: "{{ availability_zone }}"
        cinder:
          cross_az_attach: True
        libvirt:
          cpu_mode: custom
          cpu_models: Skylake-Server-noTSX-IBRS
infra_hosts: *infra
shared-infra_hosts: *infra
repo-infra_hosts: *infra
octavia-infra_hosts: *infra
magnum-infra_hosts: *infra
compute_hosts: *compute
os-infra_hosts: *infra
identity_hosts: *infra
network_hosts: *infra
#dnsaas_hosts: *infra
coordination_hosts: *infra
metrics_hosts: *infra
metering-compute_hosts: *compute
metering-infra_hosts: *infra
network-gateway_hosts: *compute
network-northd_hosts: *infra
storage-infra_hosts: *infra 
zun-compute_hosts: *zun
zun-infra_hosts: *infra
skyline_dashboard_hosts: *infra
storage_hosts:   
  infra-01:
    management_ip: 10.0.13.10
    ip: 10.0.32.4
    cinder_backends:
      rbd:
        volume_driver: cinder.volume.drivers.rbd.RBDDriver
        rbd_pool: volumes
        rbd_ceph_conf: /etc/ceph/ceph.conf
        rbd_store_chunk_size: 8
        volume_backend_name: rbd
        rbd_user: "{{ cinder_ceph_client }}"
        rbd_secret_uuid: "{{ cinder_ceph_client_uuid }}"
        report_discard_supported: true
  infra-02:
    management_ip: 10.0.13.11
    ip: 10.0.32.5
    cinder_backends:
      rbd:
        volume_driver: cinder.volume.drivers.rbd.RBDDriver
        rbd_pool: volumes
        rbd_ceph_conf: /etc/ceph/ceph.conf
        rbd_store_chunk_size: 8
        volume_backend_name: rbd
        rbd_user: "{{ cinder_ceph_client }}"
        rbd_secret_uuid: "{{ cinder_ceph_client_uuid }}"
        report_discard_supported: true
  infra-03:
    management_ip: 10.0.13.12
    ip: 10.0.32.6
    cinder_backends:
      rbd:
        volume_driver: cinder.volume.drivers.rbd.RBDDriver
        rbd_pool: volumes
        rbd_ceph_conf: /etc/ceph/ceph.conf
        rbd_store_chunk_size: 8
        volume_backend_name: rbd
        rbd_user: "{{ cinder_ceph_client }}"
        rbd_secret_uuid: "{{ cinder_ceph_client_uuid }}"
        report_discard_supported: true
haproxy_hosts: 
  lb-01:
    ip: 10.0.32.2
  lb-02:
    ip: 10.0.32.3
