cidr_networks:
  container: 10.0.18.0/24
  tunnel: 10.0.19.0/24
  storage: 10.0.16.0/24
used_ips:
  - "10.0.19.1,10.0.19.50"
  - "10.0.18.1,10.0.18.50"
  - "10.0.16.1,10.0.16.50"
global_overrides:
  internal_lb_vip_address: 10.0.18.254
  external_lb_vip_address: cloud.zeroone.tech
  management_bridge: "br-mgmt"
  provider_networks:
   - network:
        group_binds:
          - neutron_ovn_controller
        container_bridge: "br-gen"
        container_type: "veth"
        container_mtu: "9000"
        ip_from_q: "tunnel"
        type: "geneve"
        range: "1:1000"
        net_name: "geneve"
        network_interface: "bond0.1101"
   - network:
        group_binds:
          - neutron_ovn_controller
        container_bridge: "br-wan"
        container_type: "veth"
        type: "flat"
        net_name: "public"
        network_interface: "bond0.1002"
   - network:
       group_binds:
         - neutron_ovn_controller
       container_bridge: "br-vlan"
       container_type: "veth"
       type: "vlan"
       net_name: "vlan"
       range: "1120:1129"
       network_interface: "bond0"
shared-infra_hosts: &shared
  infra-01:
    ip: 10.0.18.4
  infra-02:
    ip: 10.0.18.5
  infra-03:
    ip: 10.0.18.6
repo-infra_hosts: *shared
os-infra_hosts: *shared
identity_hosts: *shared
network_hosts: *shared
storage-infra_hosts: *shared 
storage_hosts:   
  infra-01:
    ip: 10.0.18.4
    cinder_backends:
      rbd:
        volume_driver: cinder.volume.drivers.rbd.RBDDriver
        rbd_pool: volumes
        rbd_ceph_conf: /etc/ceph/ceph.conf
        rbd_store_chunk_size: 8
        volume_backend_name: rbd
        rbd_user: "{{ cinder_ceph_client }}"
        rbd_secret_uuid: "{{ cinder_ceph_client_uuid }}"
        report_discard_supported: true
  infra-02:
    ip: 10.0.18.5
    cinder_backends:
      rbd:
        volume_driver: cinder.volume.drivers.rbd.RBDDriver
        rbd_pool: volumes
        rbd_ceph_conf: /etc/ceph/ceph.conf
        rbd_store_chunk_size: 8
        volume_backend_name: rbd
        rbd_user: "{{ cinder_ceph_client }}"
        rbd_secret_uuid: "{{ cinder_ceph_client_uuid }}"
        report_discard_supported: true
  infra-03:
    ip: 10.0.18.6
    cinder_backends:
      rbd:
        volume_driver: cinder.volume.drivers.rbd.RBDDriver
        rbd_pool: volumes
        rbd_ceph_conf: /etc/ceph/ceph.conf
        rbd_store_chunk_size: 8
        volume_backend_name: rbd
        rbd_user: "{{ cinder_ceph_client }}"
        rbd_secret_uuid: "{{ cinder_ceph_client_uuid }}"
        report_discard_supported: true
haproxy_hosts: 
  lb-01:
    ip: 10.0.18.2
  lb-02:
    ip: 10.0.18.3
compute_hosts:
  compute-01:
    ip: 10.0.18.7
#  compute-02:
#    ip: 10.0.18.8
#  compute-03:
#    ip: 10.0.18.9
  compute-04:
    ip: 10.0.18.10
